
# NumPy Basics

NumPy (or Numpy) is a Linear Algebra Library for Python. You can visit https://numpy.org to know more about the library.

Today we will only learn the basics of NumPy. To get started, we need to install it

For local environment, use

    pip install numpy

For Google Colab, use

    !pip install numpy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Here, np is an alias for the keyword numpy. In Python, an alias is an alternate name for referring to the same thing.

##NumPy Arrays

Numpy provides array operations and linear algebra to Python. A Numpy array is a bit like a Python list, but supports elementwise arithmetic. For more info on why you would want to use Arrays instead of lists, check out this [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).
Here is an example of NumPy arrays:

In [2]:
x = np.asarray([1, 2, 3, 4, 5])
y = 2 * x
print(y)

[ 2  4  6  8 10]


## Built In Methods

###arange
Return evenly spaced values within a given interval.

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [5]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [7]:
np.linspace(0,50,15)

array([ 0.        ,  3.57142857,  7.14285714, 10.71428571, 14.28571429,
       17.85714286, 21.42857143, 25.        , 28.57142857, 32.14285714,
       35.71428571, 39.28571429, 42.85714286, 46.42857143, 50.        ])

### Random 

Numpy also has lots of ways to create random number arrays:

#### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [8]:
np.random.rand(5,5)

array([[0.46573528, 0.50831743, 0.61064827, 0.87354642, 0.78043843],
       [0.12939272, 0.93047858, 0.43548823, 0.91661941, 0.52288042],
       [0.91252165, 0.99153365, 0.92716971, 0.15430611, 0.69516543],
       [0.69606011, 0.23804067, 0.47285527, 0.38643427, 0.9031126 ],
       [0.31089398, 0.56954574, 0.14271024, 0.70431941, 0.44598797]])

You can also multiply the array by a constant so as to change the interval of the numbers. For example:

In [9]:
20*np.random.rand(5,5)
#the numbers now lie between 0 and 20

array([[ 6.62657121, 18.04311572,  4.23654827,  1.31125801,  5.05342726],
       [ 7.90605806,  5.69496468,  3.77642016,  5.14359904,  2.88584142],
       [ 0.39498692,  0.92250579, 16.42901317,  4.6585271 , 14.02288654],
       [ 6.5129434 ,  1.97913784,  4.99275656, 16.32291065, 11.23675723],
       [18.83498412, 14.45592878,  9.54985474,  3.97819346,  7.96706883]])

#### randn

Return a sample (or samples) from the "standard normal" distribution, unlike rand which is uniform. Visit [this link](https://www.khanacademy.org/math/statistics-probability/modeling-distributions-of-data/normal-distributions-library/a/normal-distributions-review) if you wish to know more about normal distribution.

In [10]:
np.random.randn(5,5)

array([[ 0.21074132, -1.80564121,  1.83554249,  0.11740098,  1.20280911],
       [-1.52300548,  0.37129088, -0.40279721, -0.50321779, -1.38732522],
       [ 0.09311818,  0.90831014, -1.39180525,  0.23957296,  0.03647499],
       [ 1.14175054,  0.10621249, -1.45586696,  0.4102398 , -0.00525151],
       [ 0.65213642, -0.52134816, -0.46342709, -0.33148247, -1.230787  ]])

### Reshape
Returns an array containing the same data with a new shape.

In [11]:
arr = np.arange(20)
print(arr)

print(arr.reshape(4,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### dtype
You can also grab the data type of the object in the array:

In [12]:
print(arr.dtype)
print(type(arr)) # the 'type' function tells that it is a numpy array

int64
<class 'numpy.ndarray'>


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [13]:
arr = np.arange(0,11)

#Get a value at an index
print(arr[8])

#Get values in a range
print(arr[1:5])

8
[1 2 3 4]


## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [14]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [15]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [17]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## NumPy Operations

In [18]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [20]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

NaN, standing for not a number, is a numeric data type used to represent any value that is undefined or unpresentable.

There is another data type, known as None, which is used to define a null value. It is not the same as an empty string, False, or a zero.

Assigning a value of None to a variable is one way to reset it to its original, empty state.

In [21]:
num=None
print(type(num))
print(num is np.nan)

<class 'NoneType'>
False


In [34]:
# NaN can be initialised in two ways
n1=np.nan
n2=float('nan')
print(type(n1), type(n2))

<class 'float'> <class 'float'>


In [35]:
# here is something to think about
print(n1==n1)

False


In [ ]:
# nan is NOT equal to nan
# Ponder upon this result and try to figure out why n1 is not equal to itself.

In [23]:
# 1/0 also gives a warning
# gets replaced with inf
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [24]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [26]:
#Calculating sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [27]:
#Calculating logs
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])